import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                    "#057a45",       
        "primary-fixed":              "#15803d", 
        "primary-fixed-dim":          "#0f8f5a",
        "primary-container":          "#0b9466",
        "on-primary":                 "#003824",
        "on-primary-fixed":           "#002113",
        "on-primary-fixed-variant":   "#005236",
        "on-primary-container":       "#00422b",
        "inverse-primary":            "#006c49",
        "secondary":                  "#ffb95f",
        "secondary-fixed":            "#ffddb8",
        "secondary-fixed-dim":        "#ffb95f",
        "secondary-container":        "#ee9800",
        "on-secondary":               "#472a00",
        "on-secondary-fixed":         "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "on-secondary-container":     "#5b3800",
        "tertiary":                   "#ffb3af",
        "tertiary-fixed":             "#ffdad7",
        "tertiary-fixed-dim":         "#ffb3af",
        "tertiary-container":         "#fc7c78",
        "on-tertiary":                "#650911",
        "on-tertiary-fixed":          "#410005",
        "on-tertiary-fixed-variant":  "#842225",
        "on-tertiary-container":      "#711419",
        "surface":                    "#131313",
        "surface-dim":                "#131313",
        "surface-bright":             "#3a3939",
        "surface-variant":            "#353534",
        "surface-tint":               "#4edea3",
        "surface-container-lowest":   "#0e0e0e",
        "surface-container-low":      "#1c1b1b",
        "surface-container":          "#201f1f",
        "surface-container-high":     "#2a2a2a",
        "surface-container-highest":  "#353534",
        "on-surface":                 "#e5e2e1",
        "on-surface-variant":         "#bbcabf",
        "inverse-surface":            "#e5e2e1",
        "inverse-on-surface":         "#313030",
        "background":                 "#131313",
        "on-background":              "#e5e2e1",
        "outline":                    "#86948a",
        "outline-variant":            "#3c4a42",
        "error":                      "#ffb4ab",
        "error-container":            "#93000a",
        "on-error":                   "#690005",
        "on-error-container":         "#ffdad6",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body:     ["var(--font-inter)", "sans-serif"],
        label:    ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        md:      "0.375rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "1rem",
        full:    "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
